### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by malberts**
* Drops support for < PHP 8
* Adds CI for PHP 8.0 and 8.1
  * PHP 8.2 had some failures, but since MW is unlikely to work with 8.2 I just removed it for now
  * Run result on my fork: https://github.com/malberts/http-request/actions/runs/3656906167

This primarily addresses https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5346

### CODE REVIEW

**Comment by malberts** [comment]
I realised later there was already a PR doing some of these updates: https://github.com/onoi/http-request/pull/12
However, in my case I dropped PHP 7 (the other PR supports 7.3+). Since PHP 7.4 is now completely EOL, I think this is a good time to make a breaking major release (v2).

**Comment by JeroenDeDauw** [comment]
Uh oh. Dunno if anyone has write or admin on this repo. @kghbln are you able to merge this PR?

**Comment by kghbln** [comment]
No, there is nobody left in onoi who can merge. Last time this happened for this org the respective lib was moved to SMW core.

**Comment by JeroenDeDauw** [comment]
That won't work for this repo since there are users besides SMW itself. So we need to create a copy of the repo somewhere. Perhaps on SMW org, or the ProfessionalWiki one?

**Comment by kghbln** [comment]
> Perhaps on SMW org, or the ProfessionalWiki one?

Yeah. This one looked a bit more like a general lib to me. I think that SMW is the more suitable org here.

**Comment by JeroenDeDauw** [comment]
Repo ready here: https://github.com/SemanticMediaWiki/http-request

@malberts you have admin on it

So far I just pulled and pushed master

We will also need new package name, and use the replace section like at https://github.com/JeroenDeDauw/PsrLogTestDoubles/blob/master/composer.json#L3-L5

**Comment by malberts** [comment]
Replaced by https://github.com/SemanticMediaWiki/http-request/pull/1

**Pull request closed without merging**
